# Site settings
title: "nhiroki's weblog"
description: "このブログで述べられている内容はすべて私の個人的な意見に基づくものであり、所属する組織、団体とは一切関係ありません。"
twitter_username: "nhiroki_"
github_username:  "nhiroki"
lang: ja_JP
timezone: Asia/Tokyo

url: https://nhiroki.jp
enforce_ssl: nhiroki.jp

# Post settings
permalink: /:year/:month/:day/:title

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

plugins:
  - jekyll-seo-tag
