# Site settings
title: "nhiroki's weblog"
description: "このブログで述べられている内容はすべて私の個人的な意見に基づくものであり、所属する組織、団体とは一切関係ありません。"
twitter_username: "nhiroki_"
github_username:  "nhiroki"

# Post settings
permalink: /:year/:month/:day/:title

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["smart", "tables", "no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data", "footnotes"]
